apiVersion: v1
kind: Service
metadata:
  name: lessons-api-mongo-service
  namespace: default
  labels:
    app: lessons-api-mongo
spec:
  selector:
    app: lessons-api-mongo
  ports:
    - name: mongo
      protocol: TCP
      port: 27017
      targetPort: 27017
