apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lessons
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
  destination:
    namespace: default
    name: in-cluster
  project: dev
  source:
#    path: lessons/children-apps-def/overlays/dev
    repoURL: https://github.com/daniel-codefresh/lessons-app-of-apps
    targetRevision: master
