apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lessons
  namespace: argocd
spec:
  project: production
  source:
    path: lessons/apps-definitions/children/overlays/production
  kustomize:
    # Optional image name prefix
    namePrefix: prod-
