apiVersion: v1
kind: Service
metadata:
  name: lessons-api-service
  namespace: default
  labels:
    app: lessons-api
spec:
  selector:
    app: lessons-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9000
