apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lessons
  namespace: argocd
spec:
  project: dev
  source:
    path: lessons/apps-definitions/children/overlays/dev
  kustomize:
    # Optional image name prefix
    namePrefix: dev-
