apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lessons-app
  namespace: argocd
spec:
  project: qa
  source:
    path: lessons/apps-definitions/children/overlays/qa
#    repoURL: https://github.com/daniel-codefresh/lessons-app-of-apps
#    targetRevision: master
