apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lessons
  namespace: argocd
spec:
  project: qa
  source:
    path: lessons/apps-definitions/children/overlays/qa
    kustomize:
      # Optional image name prefix
      namePrefix: qa-
